# Change these first
owner: SandersDev2021 # Your GitHub organization or username, where this repository lives
repo: monitoring # The name of this repository


sites:
# WEB APPLICATION
  - name: WEB FRONTEND 
    url: $WEB_FRONTEND_SANDERS
    
  - name: OWNCLOUD
    url: $WEB_OWNCLOUD_SANDERS
    
  - name: WEBMAIL
    url: $WEB_WEBMAIL_SANDERS
 
# SERVER AND NETWORKK
  - name: SERVER DEVELOPMENT
    check: "tcp-ping"
    url: $SERVER_DEVELOPMENT_SANDERS

  - name: SERVER FRONTEND
    check: "tcp-ping"
    url: $SERVER_FRONTEND_SANDERS

  - name: SERVER BACKEND
    check: "tcp-ping"
    url: $SERVER_BACKEND_SANDERS
  
  - name: SERVER DRC
    check: "tcp-ping"
    url: $SERVER_DRC_SANDERS
    
  - name: SERVER EMAIL
    check: "tcp-ping"
    url: $SERVER_EMAIL_SANDERS
    
  - name: SERVER DB BACKUP
    check: "tcp-ping"
    url: $SERVER_DB_BACKUP_SANDERS
    
  - name: OFFICE SANDERS
    check: "tcp-ping"
    url: $IP_PUBLIC_OFFICE_SANDERS
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: sandersdev2021.github.io/monitoring
  baseUrl: /monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
